name: 测试工作流

on:
  workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-22.04  # 指定 Ubuntu 22.04 版本

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 打印当前目录
        run: |
          echo "当前目录内容："
          ls -la
